// <auto-generated />
namespace KMA.APZRPMJ2018.RequestSimulator.DBAdapter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Lab5Migrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lab5Migrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201811242302466_Lab5Migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
